[2024-10-09 03:11:06,981] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run scheduled__2024-10-08T00:00:00+00:00 [queued]>
[2024-10-09 03:11:06,997] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run scheduled__2024-10-08T00:00:00+00:00 [queued]>
[2024-10-09 03:11:06,997] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 03:11:06,997] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-09 03:11:06,997] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 03:11:07,013] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2024-10-08 00:00:00+00:00
[2024-10-09 03:11:07,018] {standard_task_runner.py:52} INFO - Started process 223 to run task
[2024-10-09 03:11:07,022] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_run', 'scheduled__2024-10-08T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpf9kxlgyg', '--error-file', '/tmp/tmpkb5nx664']
[2024-10-09 03:11:07,022] {standard_task_runner.py:80} INFO - Job 5: Subtask dbt_run
[2024-10-09 03:11:07,087] {task_command.py:370} INFO - Running <TaskInstance: user_behaviour.dbt_run scheduled__2024-10-08T00:00:00+00:00 [running]> on host 33db15a69f99
[2024-10-09 03:11:07,166] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_behaviour
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-10-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-08T00:00:00+00:00
[2024-10-09 03:11:07,167] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-09 03:11:07,168] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-09 03:11:07,177] {subprocess.py:85} INFO - Output:
[2024-10-09 03:11:10,038] {subprocess.py:92} INFO - Running with dbt=1.0.0-b2
[2024-10-09 03:11:11,417] {subprocess.py:92} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-09 03:11:11,417] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2024-10-09 03:11:11,417] {subprocess.py:92} INFO - - models.data_pipeline.marts
[2024-10-09 03:11:11,417] {subprocess.py:92} INFO - 
[2024-10-09 03:11:11,492] {subprocess.py:92} INFO - Found 2 models, 3 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
[2024-10-09 03:11:11,494] {subprocess.py:92} INFO - 
[2024-10-09 03:11:13,239] {subprocess.py:92} INFO - 03:11:13 | Concurrency: 10 threads (target='dev')
[2024-10-09 03:11:13,239] {subprocess.py:92} INFO - 03:11:13 |
[2024-10-09 03:11:13,245] {subprocess.py:92} INFO - 03:11:13 | 1 of 1 START view model dbt_schema.stg_tpch_orders................... [RUN]
[2024-10-09 03:11:14,393] {subprocess.py:92} INFO - 03:11:14 | 1 of 1 OK created view model dbt_schema.stg_tpch_orders.............. [[32mSUCCESS 1[0m in 1.15s]
[2024-10-09 03:11:14,464] {subprocess.py:92} INFO - 03:11:14 |
[2024-10-09 03:11:14,464] {subprocess.py:92} INFO - 03:11:14 | Finished running 1 view model in 2.97s.
[2024-10-09 03:11:14,472] {subprocess.py:92} INFO - 
[2024-10-09 03:11:14,473] {subprocess.py:92} INFO - [32mCompleted successfully[0m
[2024-10-09 03:11:14,473] {subprocess.py:92} INFO - 
[2024-10-09 03:11:14,473] {subprocess.py:92} INFO - Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-10-09 03:11:14,752] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-09 03:11:14,797] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_run, execution_date=20241008T000000, start_date=20241009T031106, end_date=20241009T031114
[2024-10-09 03:11:14,840] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 03:11:14,878] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-09 05:50:34,935] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run scheduled__2024-10-08T00:00:00+00:00 [queued]>
[2024-10-09 05:50:34,948] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run scheduled__2024-10-08T00:00:00+00:00 [queued]>
[2024-10-09 05:50:34,948] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 05:50:34,949] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-09 05:50:34,949] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 05:50:34,964] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2024-10-08 00:00:00+00:00
[2024-10-09 05:50:34,967] {standard_task_runner.py:52} INFO - Started process 357 to run task
[2024-10-09 05:50:34,970] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_run', 'scheduled__2024-10-08T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpb9gxj72t', '--error-file', '/tmp/tmps43piyn3']
[2024-10-09 05:50:34,971] {standard_task_runner.py:80} INFO - Job 11: Subtask dbt_run
[2024-10-09 05:50:35,024] {task_command.py:370} INFO - Running <TaskInstance: user_behaviour.dbt_run scheduled__2024-10-08T00:00:00+00:00 [running]> on host 82b931b01445
[2024-10-09 05:50:35,097] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_behaviour
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-10-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-08T00:00:00+00:00
[2024-10-09 05:50:35,098] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-09 05:50:35,099] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-09 05:50:35,108] {subprocess.py:85} INFO - Output:
[2024-10-09 05:50:37,392] {subprocess.py:92} INFO - Running with dbt=1.0.0-b2
[2024-10-09 05:50:38,600] {subprocess.py:92} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-09 05:50:38,600] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2024-10-09 05:50:38,600] {subprocess.py:92} INFO - - models.data_pipeline.marts
[2024-10-09 05:50:38,600] {subprocess.py:92} INFO - 
[2024-10-09 05:50:38,668] {subprocess.py:92} INFO - Found 2 models, 3 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
[2024-10-09 05:50:38,670] {subprocess.py:92} INFO - 
[2024-10-09 05:50:40,171] {subprocess.py:92} INFO - 05:50:40 | Concurrency: 10 threads (target='dev')
[2024-10-09 05:50:40,172] {subprocess.py:92} INFO - 05:50:40 |
[2024-10-09 05:50:40,180] {subprocess.py:92} INFO - 05:50:40 | 1 of 1 START view model dbt_schema.stg_tpch_orders................... [RUN]
[2024-10-09 05:50:41,247] {subprocess.py:92} INFO - 05:50:41 | 1 of 1 OK created view model dbt_schema.stg_tpch_orders.............. [[32mSUCCESS 1[0m in 1.07s]
[2024-10-09 05:50:41,325] {subprocess.py:92} INFO - 05:50:41 |
[2024-10-09 05:50:41,326] {subprocess.py:92} INFO - 05:50:41 | Finished running 1 view model in 2.65s.
[2024-10-09 05:50:41,333] {subprocess.py:92} INFO - 
[2024-10-09 05:50:41,334] {subprocess.py:92} INFO - [32mCompleted successfully[0m
[2024-10-09 05:50:41,334] {subprocess.py:92} INFO - 
[2024-10-09 05:50:41,334] {subprocess.py:92} INFO - Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-10-09 05:50:42,492] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-09 05:50:42,541] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_run, execution_date=20241008T000000, start_date=20241009T055034, end_date=20241009T055042
[2024-10-09 05:50:42,568] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 05:50:42,607] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
