[2024-10-10T04:33:00.647+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-10T04:33:00.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_behaviour.dbt_run manual__2024-10-10T04:32:47.011737+00:00 [queued]>
[2024-10-10T04:33:00.694+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_behaviour.dbt_run manual__2024-10-10T04:32:47.011737+00:00 [queued]>
[2024-10-10T04:33:00.694+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-10T04:33:00.712+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-10-10 04:32:47.011737+00:00
[2024-10-10T04:33:00.718+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=328) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T04:33:00.720+0000] {standard_task_runner.py:63} INFO - Started process 336 to run task
[2024-10-10T04:33:00.720+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_run', 'manual__2024-10-10T04:32:47.011737+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpgzn7fh_c']
[2024-10-10T04:33:00.721+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask dbt_run
[2024-10-10T04:33:00.774+0000] {task_command.py:426} INFO - Running <TaskInstance: user_behaviour.dbt_run manual__2024-10-10T04:32:47.011737+00:00 [running]> on host 10fc3afc5804
[2024-10-10T04:33:00.887+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_behaviour' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-10-10T04:32:47.011737+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-10T04:32:47.011737+00:00'
[2024-10-10T04:33:00.888+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-10T04:33:00.906+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-10T04:33:00.907+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-10T04:33:00.919+0000] {subprocess.py:86} INFO - Output:
[2024-10-10T04:33:04.309+0000] {subprocess.py:93} INFO - [0m04:33:04  Running with dbt=1.8.7
[2024-10-10T04:33:05.590+0000] {subprocess.py:93} INFO - [0m04:33:05  Registered adapter: snowflake=1.8.3
[2024-10-10T04:33:05.769+0000] {subprocess.py:93} INFO - [0m04:33:05  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-10T04:33:05.769+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-10-10T04:33:05.770+0000] {subprocess.py:93} INFO - - models.data_pipeline.marts
[2024-10-10T04:33:05.948+0000] {subprocess.py:93} INFO - [0m04:33:05  Found 2 models, 3 data tests, 2 sources, 454 macros
[2024-10-10T04:33:05.951+0000] {subprocess.py:93} INFO - [0m04:33:05
[2024-10-10T04:33:07.601+0000] {subprocess.py:93} INFO - [0m04:33:07  Concurrency: 10 threads (target='dev')
[2024-10-10T04:33:07.602+0000] {subprocess.py:93} INFO - [0m04:33:07
[2024-10-10T04:33:07.620+0000] {subprocess.py:93} INFO - [0m04:33:07  1 of 1 START sql view model dbt_schema.stg_tpch_orders ......................... [RUN]
[2024-10-10T04:33:06.865+0000] {subprocess.py:93} INFO - [0m04:33:06  1 of 1 OK created sql view model dbt_schema.stg_tpch_orders .................... [[32mSUCCESS 1[0m in -0.76s]
[2024-10-10T04:33:06.870+0000] {subprocess.py:93} INFO - [0m04:33:06
[2024-10-10T04:33:06.871+0000] {subprocess.py:93} INFO - [0m04:33:06  Finished running 1 view model in 0 hours 0 minutes and 0.92 seconds (0.92s).
[2024-10-10T04:33:06.912+0000] {subprocess.py:93} INFO - [0m04:33:06
[2024-10-10T04:33:06.912+0000] {subprocess.py:93} INFO - [0m04:33:06  [32mCompleted successfully[0m
[2024-10-10T04:33:06.913+0000] {subprocess.py:93} INFO - [0m04:33:06
[2024-10-10T04:33:06.914+0000] {subprocess.py:93} INFO - [0m04:33:06  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-10-10T04:33:08.236+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-10T04:33:08.237+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-10T04:33:08.265+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_run, run_id=manual__2024-10-10T04:32:47.011737+00:00, execution_date=20241010T043247, start_date=20241010T043300, end_date=20241010T043308
[2024-10-10T04:33:08.293+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-10T04:33:08.319+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T04:33:08.322+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
